version: '3.9'
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: uid:gid
    network_mode: 'host'
    volumes:
      - ./config:/config
      - ./cache:/cache
      - /media:/media
    restart: 'unless-stopped'
